DROP TABLE if exists students;
CREATE TABLE students
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50)         NOT NULL,
    age        INTEGER             NOT NULL,
    email      VARCHAR(100) UNIQUE NOT NULL,
    major      VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

