CREATE TABLE courses
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

CREATE TABLE advanced_students
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50)         NOT NULL,
    age        INTEGER             NOT NULL,
    email      VARCHAR(100) UNIQUE NOT NULL,
    course_id  INTEGER,
    FOREIGN KEY (course_id) REFERENCES courses(id)
);

