INSERT INTO courses(name) values ('Marketing');
INSERT INTO courses(name) values ('Physics');
INSERT INTO courses(name) values ('Economics');
INSERT INTO courses(name) values ('Business');
INSERT INTO courses(name) values ('Communications');
INSERT INTO courses(name) values ('Art');
INSERT INTO courses(name) values ('History');
INSERT INTO courses(name) values ('Sociology');
INSERT INTO courses(name) values ('Music');
INSERT INTO courses(name) values ('Psychology');
INSERT INTO courses(name) values ('Geology');
INSERT INTO courses(name) values ('Computer Science');
INSERT INTO courses(name) values ('Engineering');
INSERT INTO courses(name) values ('Environmental Science');
INSERT INTO courses(name) values ('Biology');
INSERT INTO courses(name) values ('Chemistry');
INSERT INTO courses(name) values ('Political Science');
INSERT INTO courses(name) values ('English');
INSERT INTO courses(name) values ('Mathematics');
