CREATE TABLE employee
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100),
    department VARCHAR(50)
);

CREATE TABLE department
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    manager VARCHAR(100)
);

INSERT INTO employee(name, department) values ('Harry', 'Finance');
INSERT INTO employee(name, department) values ('Sally', 'Sales');
INSERT INTO employee(name, department) values ('George', 'Finance');
INSERT INTO employee(name, department) values ('Madalina', 'Sales');
INSERT INTO employee(name, department) values ('Melissa', 'HR');

INSERT INTO department(name, manager) VALUES ('Finance', 'Harry');
INSERT INTO department(name, manager) VALUES ('Sales', 'Madalina');
INSERT INTO department(name, manager) VALUES ('Production', 'Charles');