DROP TABLE IF EXISTS heroes_info;
DROP TABLE IF EXISTS heroes;

CREATE TABLE heroes_info
(
    id         VARCHAR(50),
    name       VARCHAR(50),
    eye_color  VARCHAR(50),
    race       VARCHAR(50),
    hair_color VARCHAR(50),
    height     VARCHAR(20),
    publisher  VARCHAR(50),
    skin_color VARCHAR(50),
    alignment  VARCHAR(50),
    weight     INTEGER
);

CREATE TABLE heroes
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50),
    gender     VARCHAR(50),
    eye_color  VARCHAR(50),
    race       VARCHAR(50),
    hair_color VARCHAR(50),
    height     DOUBLE PRECISION,
    publisher  VARCHAR(50),
    skin_color VARCHAR(50),
    alignment  VARCHAR(50),
    weight     INTEGER,
    created_at TIMESTAMP DEFAULT NOW()
);


insert into heroes(name, gender, eye_color, race, hair_color, height, publisher, skin_color, alignment, weight)
select name, gender, eye_color, race, hair_color, to_number(replace(height, ',', '.'), '9999.99'), publisher, skin_color, alignment, weight from heroes_info;

select * from heroes_info;
select * from heroes;

-- average height
select avg(height) from heroes
where height > 0;

-- the tallest
select name, max(height) as max_height from heroes
    group by name
    order by max_height desc
    limit 1;

-- the heaviest
select name, max(weight) as max_weight from heroes
    group by name
    order by max_weight desc
    limit 1;

-- gender counts
select gender, count(*) from heroes
    group by gender;

-- alignment counts
select alignment, count(*) from heroes
    group by alignment;

-- 5 most popular publisher
select publisher, count(*) as c from heroes
    group by publisher
    order by c desc
    limit 5;

-- 3 most popular hair color
select hair_color, count(*) as c from heroes
    where hair_color <> '-'
    group by hair_color
    order by c desc
    limit 3;

-- the most popular eye color
select eye_color, count(*) as c from heroes
    where eye_color <> '-'
    group by eye_color
    order by c desc
    limit 1;

